import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/auth-provider";
import Provider from "@/components/query-provider";
import Link from "next/link";
import logo from "@/assets/logo.png";
import Image from "next/image";
import { SunIcon } from "lucide-react";
import defaultavatar from "@/assets/default-avatar.png";
import localFont from "next/font/local";
import ModalProvider from "@/components/modal-provider";
import { Toaster } from "@/components/ui/sonner";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} font-sans antialiased `}>
        <Provider>
          <AuthProvider>
            <ModalProvider>
              <Toaster />
              <div className="flex flex-col min-h-[100vh]">
                <header className="h-15 border-b">
                  <div className="flex  h-full justify-between max-w-175 w-full px-4 m-auto">
                    <Link href={"/"} className="flex items-center gap-2">
                      <Image src={logo} alt="로고" className="h-5 w-auto" />
                      <div className="font-bold">공통 헤더</div>
                    </Link>
                    <div className="flex items-center gap-5">
                      <div className="hover:bg-muted cursor-pointer p-2 rounded-full">
                        <SunIcon />
                      </div>
                      <Image
                        src={defaultavatar}
                        alt="기본아바타"
                        className="h-6 w-auto"
                      />
                    </div>
                  </div>
                </header>
                <main className="flex-1 py-6 max-w-175 m-auto px-4 w-full">
                  {children}
                </main>
                <footer className="text-center py-10 border-t text-muted-foreground">
                  @aass6863
                </footer>
              </div>
            </ModalProvider>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
